// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using SmartMapperData.Context;
using System;

namespace SmartMapperData.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180326125939_Mapper-v1")]
    partial class Mapperv1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("SmartMapperData.Model.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Brand");

                    b.Property<string>("City");

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.Property<string>("Neighborhood");

                    b.Property<string>("PostCode");

                    b.Property<string>("Town");

                    b.Property<string>("Type");

                    b.Property<string>("Xcoor");

                    b.Property<string>("Ycoor");

                    b.HasKey("Id");

                    b.ToTable("Transport");
                });
#pragma warning restore 612, 618
        }
    }
}
